window.OGRETMEN_SEED = {
  "source": "Ogretmenler.xlsx / Bilgiler + Ogretmen + Nobet",
  "teacherCount": 31,
  "teachers": [
    {
      "id": "39778194918",
      "firstName": "ÖZNUR",
      "lastName": "ALADAĞ",
      "identityNo": "39778194918",
      "branch": "Almanca",
      "phone": "5061722308",
      "email": "oznur_bulut44@hotmail.com",
      "classAdvisor": "",
      "club": "Çevre Koruma Kulübü",
      "project": "",
      "freeDay": "Salı, Perşembe",
      "dutyDay": "Cuma",
      "dutyPlace": "Zemin",
      "scheduleNote": ""
    },
    {
      "id": "39949680356",
      "firstName": "MEHRALİ",
      "lastName": "DUMAN",
      "identityNo": "39949680356",
      "branch": "Beden Eğitimi",
      "phone": "5558375959",
      "email": "mehraliduman@gmail.com",
      "classAdvisor": "11D",
      "club": "",
      "project": "",
      "freeDay": "Salı, Cuma",
      "dutyDay": "Pazartesi",
      "dutyPlace": "Bahçe Batı",
      "scheduleNote": ""
    },
    {
      "id": "16814820314",
      "firstName": "SELÇUK",
      "lastName": "HANCIOĞLU",
      "identityNo": "16814820314",
      "branch": "Beden Eğitimi",
      "phone": "5335117242",
      "email": "selcukhancioglu61@gmail.com",
      "classAdvisor": "",
      "club": "Spor Kulübü",
      "project": "",
      "freeDay": "Pazartesi, Perşembe",
      "dutyDay": "Cuma",
      "dutyPlace": "Bahçe Batı",
      "scheduleNote": ""
    },
    {
      "id": "36652903048",
      "firstName": "NİSA",
      "lastName": "ATAY",
      "identityNo": "36652903048",
      "branch": "Bilişim Teknolojileri",
      "phone": "5558931864",
      "email": "nozalperatay@gmail.com",
      "classAdvisor": "",
      "club": "Bilişim ve İnternet Kulübü",
      "project": "",
      "freeDay": "",
      "dutyDay": "",
      "dutyPlace": "",
      "scheduleNote": ""
    },
    {
      "id": "50662435528",
      "firstName": "SERAP",
      "lastName": "ÇINAR",
      "identityNo": "50662435528",
      "branch": "Biyoloji",
      "phone": "5058832785",
      "email": "serapbudakcinar@gmail.com",
      "classAdvisor": "11A",
      "club": "",
      "project": "",
      "freeDay": "Pazartesi",
      "dutyDay": "Salı",
      "dutyPlace": "Bahçe Batı",
      "scheduleNote": ""
    },
    {
      "id": "11744723964",
      "firstName": "ZELİŞ",
      "lastName": "BUDAK",
      "identityNo": "11744723964",
      "branch": "Biyoloji",
      "phone": "5062482110",
      "email": "zelisbudakkeskin@gmail.com",
      "classAdvisor": "",
      "club": "Trafik Güvenliği ve İlkyardım Kulübü",
      "project": "",
      "freeDay": "",
      "dutyDay": "Perşembe",
      "dutyPlace": "Zemin",
      "scheduleNote": ""
    },
    {
      "id": "29305375262",
      "firstName": "ÖZLEM",
      "lastName": "SOYLU",
      "identityNo": "29305375262",
      "branch": "Coğrafya",
      "phone": "5364143033",
      "email": "emirkerem5358@gmail.com",
      "classAdvisor": "9D",
      "club": "",
      "project": "",
      "freeDay": "Cuma",
      "dutyDay": "Çarşamba",
      "dutyPlace": "1. Kat",
      "scheduleNote": ""
    },
    {
      "id": "58681156066",
      "firstName": "BAHATTİN",
      "lastName": "ASLANTAŞ",
      "identityNo": "58681156066",
      "branch": "Din Kült. ve Ahl.Bil.",
      "phone": "5058687792",
      "email": "b.aslantas@hotmail.com",
      "classAdvisor": "",
      "club": "Değerler Kulübü",
      "project": "",
      "freeDay": "Çarşamba",
      "dutyDay": "Salı",
      "dutyPlace": "1. Kat",
      "scheduleNote": ""
    },
    {
      "id": "37972858414",
      "firstName": "BİLAL",
      "lastName": "DURMAN",
      "identityNo": "37972858414",
      "branch": "Din Kült. ve Ahl.Bil.",
      "phone": "5315152238",
      "email": "bilaldurman44@gmail.com",
      "classAdvisor": "10D",
      "club": "",
      "project": "",
      "freeDay": "Pazartesi",
      "dutyDay": "Cuma",
      "dutyPlace": "1. Kat",
      "scheduleNote": ""
    },
    {
      "id": "25049286512",
      "firstName": "TAYFUN",
      "lastName": "DEVECİ",
      "identityNo": "25049286512",
      "branch": "Felsefe",
      "phone": "5541911744",
      "email": "tayfundevecii@gmail.com",
      "classAdvisor": "10C",
      "club": "",
      "project": "",
      "freeDay": "Çarşamba",
      "dutyDay": "Perşembe",
      "dutyPlace": "2. Kat",
      "scheduleNote": ""
    },
    {
      "id": "55099287870",
      "firstName": "BÜLENT",
      "lastName": "KARAASLAN",
      "identityNo": "55099287870",
      "branch": "Fizik",
      "phone": "5426463133",
      "email": "bulentkaraaslan@msn.com",
      "classAdvisor": "",
      "club": "Afet Hazırlık Kulübü",
      "project": "",
      "freeDay": "Cuma",
      "dutyDay": "Pazartesi",
      "dutyPlace": "1. Kat",
      "scheduleNote": ""
    },
    {
      "id": "18106212630",
      "firstName": "ÖZCAN",
      "lastName": "ERDEM",
      "identityNo": "18106212630",
      "branch": "Fizik",
      "phone": "5325438346",
      "email": "ozcanerdem_2@hotmail.com",
      "classAdvisor": "11B",
      "club": "",
      "project": "",
      "freeDay": "Çarşamba",
      "dutyDay": "Salı",
      "dutyPlace": "Zemin",
      "scheduleNote": ""
    },
    {
      "id": "12275702534",
      "firstName": "NURGÜL",
      "lastName": "SÖYLEMEZ",
      "identityNo": "12275702534",
      "branch": "Görsel Sanatlar",
      "phone": "5444331146",
      "email": "n-soylemez@hotmail.com",
      "classAdvisor": "",
      "club": "Görsel Sanatlar Kulübü",
      "project": "",
      "freeDay": "Salı, Perşembe",
      "dutyDay": "Cuma",
      "dutyPlace": "Bahçe Doğu",
      "scheduleNote": ""
    },
    {
      "id": "13868204046",
      "firstName": "CEM TEMEL",
      "lastName": "SARAÇOĞLU",
      "identityNo": "13868204046",
      "branch": "İngilizce",
      "phone": "5053507722",
      "email": "cts2844@gmail.com",
      "classAdvisor": "",
      "club": "Yabancı Diller Kulübü",
      "project": "",
      "freeDay": "",
      "dutyDay": "Salı",
      "dutyPlace": "Bahçe Doğu",
      "scheduleNote": ""
    },
    {
      "id": "14884333598",
      "firstName": "LEYLA",
      "lastName": "YILMAZ",
      "identityNo": "14884333598",
      "branch": "İngilizce",
      "phone": "5545675775",
      "email": "leylaylmaz02@gmail.com",
      "classAdvisor": "11C",
      "club": "",
      "project": "",
      "freeDay": "",
      "dutyDay": "Pazartesi",
      "dutyPlace": "Zemin",
      "scheduleNote": ""
    },
    {
      "id": "61705058642",
      "firstName": "GÜLCAN",
      "lastName": "ÇETİN",
      "identityNo": "61705058642",
      "branch": "Kimya/Kimya Teknolojisi",
      "phone": "5074847523",
      "email": "gulcan_soylu_cetin@hotmail.com",
      "classAdvisor": "",
      "club": "Sosyal Yardımlaşma ve Dayanışma, Çocuk Esirgeme Kulübü",
      "project": "",
      "freeDay": "Cuma",
      "dutyDay": "Perşembe",
      "dutyPlace": "Bahçe Doğu",
      "scheduleNote": ""
    },
    {
      "id": "21068414264",
      "firstName": "HACİ BAYRAM",
      "lastName": "AR",
      "identityNo": "21068414264",
      "branch": "Kimya/Kimya Teknolojisi",
      "phone": "5378461559",
      "email": "h_bayramar@hotmail.com",
      "classAdvisor": "10B",
      "club": "",
      "project": "",
      "freeDay": "",
      "dutyDay": "Pazartesi",
      "dutyPlace": "Bahçe Doğu",
      "scheduleNote": ""
    },
    {
      "id": "38941478374",
      "firstName": "BÜLENT",
      "lastName": "AKAGÜNDÜZ",
      "identityNo": "38941478374",
      "branch": "Matematik",
      "phone": "5053859719",
      "email": "baka_44@hotmail.com",
      "classAdvisor": "9C",
      "club": "",
      "project": "",
      "freeDay": "Salı",
      "dutyDay": "Çarşamba",
      "dutyPlace": "Bahçe Batı",
      "scheduleNote": ""
    },
    {
      "id": "51847389612",
      "firstName": "HASAN",
      "lastName": "CANYURT",
      "identityNo": "51847389612",
      "branch": "Matematik",
      "phone": "5057857450",
      "email": "hasancanyurt@hotmail.com",
      "classAdvisor": "12A",
      "club": "",
      "project": "",
      "freeDay": "Perşembe",
      "dutyDay": "Salı",
      "dutyPlace": "2. Kat",
      "scheduleNote": ""
    },
    {
      "id": "32104440918",
      "firstName": "MEHMET HANİFİ",
      "lastName": "GELERİ",
      "identityNo": "32104440918",
      "branch": "Matematik",
      "phone": "5053148222",
      "email": "mehmethg@hotmail.com",
      "classAdvisor": "10A",
      "club": "",
      "project": "",
      "freeDay": "Pazartesi",
      "dutyDay": "Perşembe",
      "dutyPlace": "1. Kat",
      "scheduleNote": ""
    },
    {
      "id": "51745387246",
      "firstName": "YILDIRAY",
      "lastName": "YILDIRIM",
      "identityNo": "51745387246",
      "branch": "Matematik",
      "phone": "5059134585",
      "email": "Ottoman1574@yandex.com",
      "classAdvisor": "",
      "club": "Kızılay ve Kan Bağışı Kulübü",
      "project": "",
      "freeDay": "Çarşamba",
      "dutyDay": "Pazartesi",
      "dutyPlace": "2. Kat",
      "scheduleNote": ""
    },
    {
      "id": "16849254818",
      "firstName": "RAMAZAN",
      "lastName": "İLHAN",
      "identityNo": "16849254818",
      "branch": "Müdür / Fizik",
      "phone": "5054003286",
      "email": "ramazanilhan0644@gmail.com",
      "classAdvisor": "",
      "club": "",
      "project": "",
      "freeDay": "Pazartesi, Salı, Çarşamba",
      "dutyDay": "",
      "dutyPlace": "",
      "scheduleNote": ""
    },
    {
      "id": "26303235666",
      "firstName": "ÜMİT",
      "lastName": "ATABEY",
      "identityNo": "26303235666",
      "branch": "Müdür Başyardımcısı / Türk Dili ve Edebiyatı",
      "phone": "5059237608",
      "email": "umitatabey4444@gmail.com",
      "classAdvisor": "",
      "club": "",
      "project": "",
      "freeDay": "Salı, Çarşamba, Cuma",
      "dutyDay": "",
      "dutyPlace": "",
      "scheduleNote": ""
    },
    {
      "id": "24836297168",
      "firstName": "HACER",
      "lastName": "ER",
      "identityNo": "24836297168",
      "branch": "Müdür Yardımcısı / Felsefe",
      "phone": "5056682584",
      "email": "elha.hacer@gmail.com",
      "classAdvisor": "",
      "club": "",
      "project": "",
      "freeDay": "Pazartesi, Salı, Çarşamba, Perşembe, Cuma",
      "dutyDay": "",
      "dutyPlace": "",
      "scheduleNote": ""
    },
    {
      "id": "15643689888",
      "firstName": "ZÜLFÜ",
      "lastName": "TAŞKESEN",
      "identityNo": "15643689888",
      "branch": "Müdür Yardımcısı / Türk Dili ve Edebiyatı",
      "phone": "5055731243",
      "email": "ayustasi@gmail.com",
      "classAdvisor": "",
      "club": "",
      "project": "",
      "freeDay": "Pazartesi, Çarşamba, Cuma",
      "dutyDay": "",
      "dutyPlace": "",
      "scheduleNote": ""
    },
    {
      "id": "40522761546",
      "firstName": "PINAR",
      "lastName": "DEMİRHAN AKGÖK",
      "identityNo": "40522761546",
      "branch": "Müzik",
      "phone": "5386345253",
      "email": "dempir_44@outlook.com",
      "classAdvisor": "",
      "club": "Müzik Kulübü",
      "project": "",
      "freeDay": "Salı, Perşembe",
      "dutyDay": "Cuma",
      "dutyPlace": "2. Kat",
      "scheduleNote": ""
    },
    {
      "id": "5387974463",
      "firstName": "FERAT",
      "lastName": "DALAMAN",
      "identityNo": "5387974463",
      "branch": "Rehberlik",
      "phone": "5387974463",
      "email": "dalamanferat@gmail.com",
      "classAdvisor": "",
      "club": "",
      "project": "",
      "freeDay": "Pazartesi, Salı, Çarşamba, Perşembe, Cuma",
      "dutyDay": "",
      "dutyPlace": "",
      "scheduleNote": ""
    },
    {
      "id": "20524837562",
      "firstName": "MURAT",
      "lastName": "KATI",
      "identityNo": "20524837562",
      "branch": "Tarih",
      "phone": "5065426935",
      "email": "muratkati23@hotmail.com",
      "classAdvisor": "12B",
      "club": "",
      "project": "",
      "freeDay": "",
      "dutyDay": "Perşembe",
      "dutyPlace": "Bahçe Batı",
      "scheduleNote": ""
    },
    {
      "id": "32849030672",
      "firstName": "HULUSİ",
      "lastName": "POLAT",
      "identityNo": "32849030672",
      "branch": "Türk Dili ve Edebiyatı",
      "phone": "5054796076",
      "email": "hulupol@hotmail.com",
      "classAdvisor": "9B",
      "club": "",
      "project": "",
      "freeDay": "Cuma",
      "dutyDay": "Çarşamba",
      "dutyPlace": "Bahçe Doğu",
      "scheduleNote": ""
    },
    {
      "id": "56761558700",
      "firstName": "MEHMET",
      "lastName": "GÜRAN",
      "identityNo": "56761558700",
      "branch": "Türk Dili ve Edebiyatı",
      "phone": "5054575584",
      "email": "c_m_sena@hotmail.com",
      "classAdvisor": "",
      "club": "Bilim-Fen ve Teknoloji Kulübü",
      "project": "",
      "freeDay": "Pazartesi",
      "dutyDay": "Çarşamba",
      "dutyPlace": "Zemin",
      "scheduleNote": ""
    },
    {
      "id": "13051329600",
      "firstName": "MEHMET SIRAÇ",
      "lastName": "ÇELİK",
      "identityNo": "13051329600",
      "branch": "Türk Dili ve Edebiyatı",
      "phone": "5398994271",
      "email": "hayat1877@hotmail.com",
      "classAdvisor": "9A",
      "club": "",
      "project": "",
      "freeDay": "Salı",
      "dutyDay": "Çarşamba",
      "dutyPlace": "2. Kat",
      "scheduleNote": ""
    }
  ]
};
